plugins {
    id 'com.android.application'
}

android {
    namespace 'android.kimyona.zgang'
    compileSdk 34

    defaultConfig {
        applicationId "android.kimyona.zgang"
        minSdk 1
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // NOTHING.
}